[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[programs.localnet]
spl-vault = "1cBTAQ7XtS2MuhGanUh66rMWs92YWm1z2xBoERGj6gh"

[scripts]
# Initialize a vault (Only the owner can perform this action)
initialize-vault = "npm test -- tests/components/initVault.js"

# Create a reward schedule (APR) (Owner only)
create-reward-schedule = "npm test -- tests/components/createTimeRewards.js"

# Add rewards to the pool (For payout to stakers, Owner only)
add-rewards = "npm test -- tests/components/addRewards.js"

# Initialize a user account within the vault (Supports multiple accounts per user)
initialize-user-account = "npm test -- tests/components/initAccount.js"

# Stake tokens (Amount staked is distributed across all the user's accounts)
stake-tokens = "npm test -- tests/components/stakeTokens.js"

# Update vault parameters (Rewards, lockup options/durations, etc.)
update-vault = "npm test -- tests/components/updateVault.js"

# Store earned rewards since the last update
store-rewards = "npm test -- tests/components/storeRewards.js"

# Withdraw stored rewards
withdraw-rewards = "npm test -- tests/components/withdrawRewards.js"
